conky.config={
    update_interval = 60,            -- the update interval


    double_buffer = true,           -- enbale double buffering
    own_window = true,              -- create a separate window
    own_window_type = 'override',   -- 'override' so it draws properly on a WM or KDE
    own_window_transparent = false, -- disable window transparancy so I can control it with 'argb'
    own_window_hints = 'undecorated,sticky,below,skip_taskbar,skip_pager', -- window hints
    own_window_class = 'Conky',

    
    -- enable transparancy
    own_window_argb_visual = true,
    own_window_argb_value = 220,

    out_to_console = true,          -- print the output to the console
    out_to_stderr = false,

    
    -- main config
    alignment = 'top_left',         -- top_right | top_left | top_middle | bottom_right | bottom_left | bottom_middle | middle_right | middle_left | middle_middle
    use_xft = true,
    font = 'monospace:size=10:embolden=true',
    use_spacer = 'right',


    -- color config (you define colors here)
    own_window_colour = '08090e',
    color0 = 'CF8DD2',
    color1 = 'AAAAFF',
    color2 = '2A2AFF',
    color3 = '41B8F2',
};

conky.text = [[
    $color1${exec curl "wttr.in/?0quT.png"}  
$color2$hr

    ${color3}Feels like: $color0${exec curl "wttr.in/?format=%f&u"}$color3,
    Humidity: $color0${exec curl "wttr.in/?format=%h"}$color3,
    Moon: $color0${font Symbola:size=10}${exec curl "wttr.in/?format=%m"}$font ${exec curl "wttr.in/?format=%M"}$color3,

    ⬆${font Twemoji:size=10}☀$font: ${exec curl "wttr.in/?format=%S&u"}, $font⬇${font Twemoji:size=10}☀$font: ${exec curl "wttr.in/?format=%s&u"}
${color2}System $hr

    $color3${font monospace:size=12}uptime: $color0$uptime_short
    $font
]]
