opacity-rule = [
    "98:class_g = 'qutebrowser' && focused",
    "98:class_g = 'qutebrowser' && !focused",
    "96:class_g = 'dmenu' && focused",
    "96:class_g = 'dmenu' && !focused",
    "78:class_g = 'i3lock' && !focused",
]
unredir-if-possible = false;
vsync = true;
backend = "xrender";
