opacity-rule = [
    "98:class_g = 'qutebrowser' && focused",
    "98:class_g = 'qutebrowser' && !focused",
    "96:class_g = 'dmenu' && focused",
    "96:class_g = 'dmenu' && !focused",
    "78:class_g = 'i3lock' && !focused",
    "96:class_g = 'discord' && focused",
    "92:class_g = 'discord' && !focused",
    "96:class_g = 'st-256color' && focused",
    "96:class_g = 'st-256color' && !focused",
]
unredir-if-possible = false;
vsync = false;
backend = "xrender";
